apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredefaultapp-deploy
  namespace: app 
spec:
  selector:
    matchLabels:
      app: azuredefaultapp
  replicas: 1
  template:
    metadata:
      labels:
        app: azuredefaultapp
    spec:
      containers:
      - name: azuredefaultapp
        image: kodeval/azuredefaultapp
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: azuredefaultapp-svc
  namespace: app
spec:
  selector:
    app: azuredefaultapp
  ports:
  - port: 80
  type: ClusterIP # LoadBalancer # NodePort # 